### ISSUE TITLE
Misspelling of the word "period"

### ISSUE THREAD

**Issue by cameff** [reapp/reapp.github.io#2]
On this page: http://reapp.io/start.html#why under the **why** there is a small misspelling pointed out below:  

_From those two apps, over a **peried** of months, we extracted a set of packages, ensuring to keep each of them completely independent. It was an experiment in seeing if a framework was necessary.*_ 
  
I tried looking here (https://github.com/reapp/reapp.github.io/blob/master/pages/start.html), but it didn't seem like it was 1 to 1 to what is currently live.

**Comment by natew** [comment]
Thank you. Should be fixed on the site (once this push goes through).
