### ISSUE TITLE
Lots of grammar/spelling errors in getting started guide

### ISSUE THREAD

**Issue by aendra-rininsland** [reapp/reapp.github.io#8]
> For now, it simply makes a bare clone of a repo we keep updated with the current best-practice. The goal is eventually to have a variety of baseline repo's to choose from.
- "best-practice" should probably be plural and non-hyphenated ("best practices").
- "repo's" should be "repos" (non-possessive).

Those are the first two that jumped out at me, there are a few more I've noticed in my very cursory, 2:30 a.m. reading of it. Happy to do a PR if desired!

**Comment by jhopper28** [comment]
Fixed with latest update.
